In [2]:
import torch

## Basics of a Tensor

In [3]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [4]:
print(f'a = {a} \n b = {b}')

a = tensor([[0.8045, 0.9874, 0.9373],
        [0.9490, 0.8959, 0.5034]]) 
 b = tensor([[0.2992, 0.4284, 0.3724],
        [0.0605, 0.5502, 0.3727]])


### Math Operations - add, sub, mul

In [5]:
add = a + b
sub = a - b
mul = a * b

In [6]:
print(f'add = {add} \n sub = {sub} \n mul = {mul}')

add = tensor([[1.1037, 1.4158, 1.3097],
        [1.0096, 1.4460, 0.8761]]) 
 sub = tensor([[0.5053, 0.5590, 0.5649],
        [0.8885, 0.3457, 0.1307]]) 
 mul = tensor([[0.2407, 0.4230, 0.3490],
        [0.0575, 0.4929, 0.1876]])


### Tensor Transformations - Transpose

In [7]:
a_transpose = a.T
print(f'a_transpose = {a_transpose}')

a_transpose = tensor([[0.8045, 0.9490],
        [0.9874, 0.8959],
        [0.9373, 0.5034]])


In [8]:
print(f'a.shape = {a.shape}')
print(f'a_transpose.shape = {a_transpose.shape}')

a.shape = torch.Size([2, 3])
a_transpose.shape = torch.Size([3, 2])


### Tensor Transformations - Matrix Multiplication

In [9]:
dot_AB = a @ b.T
dot_BA = a.T @ b

In [10]:
print(f'dot_AB = {dot_AB}\ndot_BA = {dot_BA}')

dot_AB = tensor([[1.0128, 0.9413],
        [0.8552, 0.7380]])
dot_BA = tensor([[0.2982, 0.8668, 0.6533],
        [0.3497, 0.9159, 0.7016],
        [0.3109, 0.6785, 0.5367]])


In [11]:
print(f'dot_AB = {dot_AB.shape}\ndot_BA = {dot_BA.shape}')

dot_AB = torch.Size([2, 2])
dot_BA = torch.Size([3, 3])


### Broadcasting - Tensor operations of different shapes

In [12]:
a1 = torch.tensor([[1], [2], [3]])
b1 = torch.tensor([4,5,6])
print(f'a1.shape = {a1.shape}\nb1.shape = {b1.shape}')

a1.shape = torch.Size([3, 1])
b1.shape = torch.Size([3])


In [13]:
c1 = a1 + b1
print(f'c1.shape = {c1.shape}')
print(f'c1 = {c1}')

c1.shape = torch.Size([3, 3])
c1 = tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])


In [14]:
c2 = b1 + a1
print(f'c2.shape = {c2.shape}')
print(f'c2 = {c2}')

c2.shape = torch.Size([3, 3])
c2 = tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])


### Batch Matrix Multiplication

In [15]:
batch_size = 10
a3 = torch.randn(batch_size, 3, 4) # 10 matrices of size [3,4]
b3 = torch.randn(batch_size, 4, 5) # 10 matrices of size [4,5]
print(f'a3.shape = {a3.shape}')
print(f'a3 = {a3}')
print(f'b3.shape = {b3.shape}')
print(f'b3 = {b3}')

a3.shape = torch.Size([10, 3, 4])
a3 = tensor([[[ 2.3360, -0.0274, -0.1563,  1.5749],
         [-0.6632, -0.1874,  0.5805,  1.2458],
         [ 0.8472,  0.6005, -1.4414,  1.2612]],

        [[ 0.0945,  0.7324,  1.3906, -0.8593],
         [ 0.1183, -0.2525, -0.7881, -1.6364],
         [-0.4780,  0.9723,  1.1170, -2.1341]],

        [[ 0.8683,  0.9897,  0.8799,  0.3443],
         [ 0.3664, -0.6289, -0.3326,  0.6086],
         [ 0.0838, -0.4225, -0.7673,  1.8372]],

        [[-0.9328, -0.4635,  0.2919,  0.4985],
         [ 2.0369, -0.5386,  0.2170, -0.3858],
         [-1.8497, -0.0617,  0.2229, -0.1178]],

        [[ 0.8324, -2.0087, -1.7489,  1.1563],
         [ 0.2321, -0.4063,  0.7073, -0.6054],
         [ 0.1911,  0.0424,  0.3261, -0.1659]],

        [[ 1.1871, -1.6834,  0.4922, -1.0649],
         [-0.4096, -1.2203, -1.2248,  2.0031],
         [-1.2452,  1.7600,  2.4892, -1.6109]],

        [[-0.1903, -0.5448, -1.0376,  2.7409],
         [ 0.2325,  0.9640, -0.4168, -0.4823],
         

In [16]:
c3 = a3 @ b3

In [17]:
print(f'c3.shape = {c3.shape}')
print(f'c3 = {c3}')

c3.shape = torch.Size([10, 3, 5])
c3 = tensor([[[ 3.4321,  2.2704,  0.5689,  0.1775, -1.4435],
         [-0.6303, -1.4701,  0.5369,  2.8866,  3.2019],
         [ 0.9613,  0.0264,  1.5858, -1.3325, -0.0413]],

        [[-0.1444, -2.7869, -2.5426,  2.1132, -4.3835],
         [ 0.7872, -2.9367,  0.8784, -0.7292,  0.4522],
         [ 0.3206, -5.3647, -2.4412,  2.4869, -3.7783]],

        [[-0.1618, -0.3161, -0.7240,  0.5355, -3.0845],
         [ 0.0922,  0.4664,  0.9933, -0.9653, -0.6852],
         [ 0.3895, -0.2906,  0.9694, -0.5912, -0.5008]],

        [[-0.5807,  0.4285, -0.5535,  1.9304, -2.0459],
         [ 2.1306,  0.2315, -1.9426, -0.9477,  3.3795],
         [-1.6953,  0.5420, -0.5511,  1.5560, -3.5835]],

        [[-3.2294, -1.1550,  4.3617, -1.8805,  2.6828],
         [ 0.3220, -0.8326, -1.2287, -1.1705, -1.3123],
         [ 0.4499, -0.1247, -0.4492, -0.0973, -0.2303]],

        [[ 2.6179,  0.0419,  2.0898, -2.1523, -4.4216],
         [ 2.0469,  3.8244,  5.0343,  1.7803,  2.5013],

### Batch Matrix Multiplication with Broadcasting

In [18]:
d = torch.randn(4,5) # no batch, so single matrix of [4,5]
e = a3 @ d # with broadcasting

In [19]:
print(f'e.shape = {e.shape}')
print(f'e = {e}')

e.shape = torch.Size([10, 3, 5])
e = tensor([[[ 1.9431e+00,  1.0326e+00, -4.5895e-01,  1.5558e+00, -3.5060e+00],
         [ 2.1611e-01,  2.4777e+00, -5.0582e-02, -8.4300e-01,  2.7535e+00],
         [-5.5789e-01,  1.2349e+00,  3.0550e+00, -3.6193e+00, -1.9111e+00]],

        [[-2.9498e-01, -1.7533e+00, -1.8972e+00,  4.8351e+00,  1.1670e+00],
         [-2.5564e-01, -2.5654e+00,  3.8779e-02, -2.3729e-01, -2.5012e+00],
         [-1.3444e+00, -3.5155e+00, -1.4975e+00,  4.6160e+00,  1.1503e+00]],

        [[-7.0214e-02, -4.3116e-01, -6.7488e-01,  3.5094e+00,  1.7673e-01],
         [ 9.6558e-01,  1.0036e+00, -8.6191e-02, -1.0808e+00, -1.0054e+00],
         [ 5.1283e-01,  3.0591e+00,  1.6494e+00, -3.8749e+00,  1.1520e-01]],

        [[ 8.6264e-02,  1.5790e+00, -1.1579e-01, -1.3021e+00,  2.2157e+00],
         [ 2.1797e+00, -1.6894e+00, -2.4428e+00,  3.9798e+00, -4.3157e+00],
         [-1.2037e+00,  1.0143e+00,  7.0278e-01, -2.1627e+00,  3.6905e+00]],

        [[ 2.3812e+00,  2.1752e+00,  6.1592

In [20]:
torch.cuda.is_available()

True

In [21]:
torch.version.cuda

'13.0'

### Tensor Patterns

In [22]:
data = [[1,2,3],[4,5,6]]
myt = torch.tensor(data)
print(f'myt = {myt}')
print(f'shape: {myt.shape}')

myt = tensor([[1, 2, 3],
        [4, 5, 6]])
shape: torch.Size([2, 3])


In [23]:
shape = (2,3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)
rando = torch.randn(shape)

print(f'ones = {ones} \n of shape: {ones.shape}')
print(f'zeros = {zeros} \n of shape: {zeros.shape}')
print(f'rando = {rando} \n of shape: {rando.shape}')

ones = tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 of shape: torch.Size([2, 3])
zeros = tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 of shape: torch.Size([2, 3])
rando = tensor([[ 0.2077, -1.1527,  0.2968],
        [-0.4120, -0.0181, -0.1320]]) 
 of shape: torch.Size([2, 3])


In [24]:
temp = torch.tensor([[1,2],[3,4]])
simi = torch.rand_like(temp, dtype=torch.float)
print(f'temp = {temp} \n of shape: {temp.shape}')
print(f'simi = {simi} \n of shape: {simi.shape}')

temp = tensor([[1, 2],
        [3, 4]]) 
 of shape: torch.Size([2, 2])
simi = tensor([[0.1953, 0.8156],
        [0.3990, 0.0156]]) 
 of shape: torch.Size([2, 2])


In [28]:
print(f'simi = {simi} \n of shape: {simi.shape} \n with data type: {simi.dtype} \n device: {simi.device}')

simi = tensor([[0.1953, 0.8156],
        [0.3990, 0.0156]]) 
 of shape: torch.Size([2, 2]) 
 with data type: torch.float32 
 device: cpu


#### Data vs Parameter
* __Data__ is simple Tensor with Shape, Type & Device Type.
* __Parameter__ is where autograd keeps track of all operations done on it. Enable using __requires_grad=True__.

In [29]:
x_data = torch.randn(2,2)
print(f'x_data = {x_data} \n of shape: {x_data.shape} \n with data type: {x_data.dtype} \n device: {x_data.device}')

x_data = tensor([[-0.7177,  1.6693],
        [ 0.3429, -0.4579]]) 
 of shape: torch.Size([2, 2]) 
 with data type: torch.float32 
 device: cpu


In [30]:
w_data = torch.tensor([[1.,2.], [3.,4.]], requires_grad=True)
print(f'w_data = {w_data} \n of shape: {w_data.shape} \n with data type: {w_data.dtype} \n device: {w_data.device}')

w_data = tensor([[1., 2.],
        [3., 4.]], requires_grad=True) 
 of shape: torch.Size([2, 2]) 
 with data type: torch.float32 
 device: cpu


In [31]:
print(f'x_data: {x_data.requires_grad}')
print(f'w_data: {w_data.requires_grad}')

x_data: False
w_data: True


### Tracking the Tensor with Gradient
__Goal:__ Compute z = x * y, where y = a + b

In [32]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

In [35]:
y = a + b
z = x * y

print(f'z: {z}')

z: 20.0


print(f'grad_fn for z: {z.grad_fn}')
print(f'grad_fn for y: {y.grad_fn}')
print(f'grad_fn for a: {a.grad_fn}')

As expected the breadcrumbs (grad_fn) shows that __z__ resulted from a Multiplication, __y__ resulted from an Addition and __a__ was an input (not an operation). When we call __loss.backward()__, PyTorch will walk thru this trail of breadcrumbs to calculate the gradients.

### Think of Tensor as the Noun, Autograd as a Nervous System & Operations

### Reduction - mean, sum, min, max

In [37]:
scores = torch.tensor([[10.,20.,30.],[5.,10.,15.]])
scores_mean = scores.mean() # adds all elements and in this case divides by 6
scores_mean

tensor(15.)

### dim argument - determines which direction to collapse
* dim=0 => collapses the rows, i.e., operates "vertically"
* dim=1 => collapses the columns, i.e., operates "horizontally"

#### Setup - marks of 2 students across 3 subjects

In [38]:
scores1 = torch.tensor([[10.,20.,30.],[5.,10.,15.]])

avg_per_subject = scores1.mean(dim=0) #collapse student dimension
avg_per_student = scores1.mean(dim=1) #collapse subject dimension

print(f'avg_per_subject: {avg_per_subject}')
print(f'avg_per_student: {avg_per_student}')

avg_per_subject: tensor([ 7.5000, 15.0000, 22.5000])
avg_per_student: tensor([20., 10.])


### Indexing

In [39]:
x = torch.arange(12).reshape(3,4)
print(f'x: {x}')

x: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [42]:
x[:,:]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [41]:
x[:,2]

tensor([ 2,  6, 10])

In [43]:
x[2,:]

tensor([ 8,  9, 10, 11])

### Dynamic Indexing
Finding index of the highest value

In [44]:
scores_2 = torch.tensor([
    [10, 0, 5, 20, 1],
    [1, 30, 2, 5, 0]
])

In [49]:
torch.argmax(scores_2) # gives the index of highest in a single row matrix

tensor(6)

In [50]:
torch.argmax(scores_2, dim=0) # gives the indexes for each column 

tensor([0, 1, 0, 0, 0])

In [51]:
torch.argmax(scores_2, dim=1) # gives the index for each row

tensor([3, 1])

### Torch Gather

In [52]:
data = torch.tensor([
    [10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33]
])

indices_to_select = torch.tensor([[2], [0], [3]])
selected_values = torch.gather(data, dim=1, index=indices_to_select)
selected_values

tensor([[12],
        [20],
        [33]])

In [54]:
indices_to_select1 = torch.tensor([[2], [0], [1]])
torch.gather(data, dim=0, index=indices_to_select1)

tensor([[30],
        [10],
        [20]])

In [64]:
indices_to_select2 = torch.tensor([[2]])
torch.gather(data, dim=0, index=indices_to_select2)

tensor([[30]])

In [70]:
torch.randint(0,9,(2,))

tensor([0, 6])

In [71]:
torch.randint(0,9,(2,3))

tensor([[4, 8, 1],
        [5, 3, 2]])

In [72]:
torch.randint(0,9,(2,3,4))

tensor([[[5, 3, 8, 4],
         [1, 8, 2, 7],
         [7, 1, 6, 1]],

        [[1, 2, 4, 7],
         [6, 7, 7, 7],
         [8, 8, 7, 5]]])

In [74]:
torch.randint(1,10,(2,3,4,5))

tensor([[[[9, 4, 7, 2, 9],
          [8, 5, 2, 2, 6],
          [1, 7, 9, 8, 1],
          [6, 9, 7, 5, 6]],

         [[8, 3, 8, 1, 7],
          [3, 3, 6, 6, 9],
          [7, 3, 6, 6, 4],
          [8, 5, 4, 3, 5]],

         [[8, 8, 2, 9, 7],
          [1, 5, 9, 6, 4],
          [9, 7, 8, 1, 2],
          [4, 6, 7, 7, 1]]],


        [[[4, 4, 5, 3, 1],
          [2, 9, 7, 5, 6],
          [6, 4, 6, 2, 8],
          [5, 1, 7, 3, 6]],

         [[1, 6, 7, 2, 9],
          [6, 8, 2, 6, 9],
          [5, 5, 9, 5, 7],
          [7, 7, 3, 4, 7]],

         [[2, 8, 2, 4, 3],
          [6, 8, 7, 8, 5],
          [2, 9, 7, 8, 7],
          [7, 1, 8, 7, 5]]]])

## Tensor Reshaping

In [ ]:
a4 = torch.randn(size=[2,3,4])
a4_flat = a4.reshape(-1)